"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const movieControler_1 = require("../constroller/movies/movieControler");
const movieRoutes = (0, express_1.Router)();
movieRoutes.get("/movie", movieControler_1.moviecontroller.getMovies);
movieRoutes.get("/movie/:id", movieControler_1.moviecontroller.getMovieById);
movieRoutes.post("/movie", movieControler_1.moviecontroller.postMovie);
movieRoutes.put("/movie/:id", movieControler_1.moviecontroller.putMovie);
movieRoutes.delete("/movie/:id", movieControler_1.moviecontroller.deleteMovie);
exports.default = movieRoutes;
